const defaultChessConfig = {
  engine: "komodo",

  elo: 3500,
  coach: 999,
  hideArrow: false,
  lines: 5,
  colors: ["#0000ff", "#00ff00", "#FFFF00", "#f97316", "#ff0000"],
  depth: 10,
  depth2: 10,
  delay0: 0,
  delay: 5000,
  style: "Default",
  autoMove: false,
  floatingBtn: false,
  speach: false,
  moveClassification: false,
  accuracy: false,
  autoStart: false,
  winningMove: false,
  showEval: false,
  preview: "None",
  onlyShowEval: false,
  key: "a",
  key2: "z",
  hints: [
    "brilliant",
    "greatFind",
    "best",
    "excellent",
    "good",
    "book",
    "inaccuracy",
    "mistake",
    "miss",
    "blunder",
    "forced",
  ],

  // special stockfish 6
  st6_mobilityMid: 100,
  st6_mobilityEnd: 100,
  st6_pawnStructureMid: 100,
  st6_pawnStructureEnd: 100,
  st6_passedPawnsMid: 100,
  st6_passedPawnsEnd: 100,
  st6_kingSafety: 100,
};
